const text = [
  "Accumsan eu in sociosqu risus, tincidunt platea urna. Primis suspendisse consequat elementum et habitasse a rhoncus. Congue dictum lacinia cubilia vehicula ultricies integer. Fusce lacus hendrerit congue cursus nisl. Class semper platea malesuada iaculis accumsan nec a nec. Placerat pharetra sodales ipsum taciti interdum finibus. Torquent massa magnis porttitor rutrum sollicitudin orci, nisi fringilla tortor. Eleifend maximus ridiculus a fames turpis ridiculus. Non phasellus tortor hac nascetur nisi maximus proin.",
  "Pellentesque vehicula dignissim molestie fames lobortis! Magna accumsan conubia aliquam habitasse ultrices. Rhoncus faucibus vitae aptent scelerisque ad sem. Eu pulvinar volutpat at integer himenaeos diam urna facilisis. Aquis curae tellus venenatis erat nisl. Platea praesent natoque maecenas aliquam euismod litora. Dui ipsum porta libero facilisis integer; maximus ultrices est. Per potenti justo praesent fusce hac. Nisl convallis sem pulvinar ullamcorper laoreet congue dictumst mauris commodo. Metus magna sed dignissim vulputate adipiscing aliquet.",
  "Ultricies commodo inceptos erat rutrum eros gravida semper. Cubilia ex dapibus potenti magna non sit? Luctus ad sociosqu luctus potenti platea class orci. Mauris sapien egestas cubilia euismod commodo odio. Ullamcorper turpis velit, nam ad platea consectetur aliquam. In fermentum hac rhoncus condimentum bibendum facilisis consectetur luctus. Porttitor dolor tortor nam ad quisque gravida condimentum aliquam.",
  "Penatibus consequat primis arcu fames sem viverra mus. Venenatis finibus curae ad mollis gravida ac. In ridiculus interdum convallis neque, amet eleifend a. Enim magna ex dolor nisi velit consectetur ac purus. Pretium mollis nibh malesuada parturient orci gravida curae interdum. Sodales ligula mus erat vivamus vivamus arcu cras. Metus velit finibus duis; cubilia vitae leo arcu malesuada.",
  "Non senectus malesuada magnis ac per pulvinar vestibulum ullamcorper placerat. Sagittis mattis quis torquent senectus nascetur ad ultrices. Vitae fermentum nec cras facilisi litora. Elementum donec porttitor condimentum eros molestie justo. Eleifend quam dolor velit sollicitudin consequat faucibus fames. Porta ligula donec ut conubia duis natoque nisi libero. At quis rhoncus in eget taciti dictum lectus nibh? Odio finibus per pulvinar a litora sem ut. Fringilla phasellus dolor elementum senectus sapien fermentum.",
  "Sociosqu in adipiscing; lorem proin enim dictumst nisi! Ullamcorper auctor tortor facilisi ultricies aliquet ipsum vel pharetra. Condimentum enim urna euismod lacus; facilisis porta pulvinar. Hendrerit diam libero pellentesque suspendisse ac, nascetur habitant? Odio ac quam turpis nisi magnis malesuada felis. Cursus feugiat maximus pulvinar penatibus maecenas nascetur. Parturient fames augue risus lacus primis magnis torquent.",
  "Per leo volutpat cras convallis massa eu primis sodales. Class fames eros potenti tellus ridiculus volutpat nascetur. Venenatis efficitur dictumst sollicitudin dolor; laoreet finibus. Iaculis at ipsum habitant convallis tristique suscipit. Tincidunt purus mauris nostra non placerat. Efficitur elit sapien adipiscing facilisis ridiculus, interdum class. Aenean suscipit pulvinar proin montes dis natoque; orci odio etiam. Penatibus himenaeos est senectus dui, risus litora.",
  "Nisl nibh aliquet eros ac hac ligula. At per dolor litora orci efficitur justo natoque nulla. Dictum suscipit suspendisse sem imperdiet augue ad. Sagittis ullamcorper cubilia phasellus curae ac mi nisl nibh? Nunc libero enim maximus blandit; taciti torquent! Erat venenatis ex feugiat diam scelerisque pulvinar phasellus, integer amet. Inceptos integer libero est justo ligula dictum. Cubilia gravida aptent a velit dolor sit habitasse.",
];
export default text;
